var stringObjects = [
  {name: 'Andrew Wallace',
   intro: 'I own a technology consultation company that specializes in computer consulatation that covers purchasing, training, repairs, implementation, and upgrading. Additionally I was a multimedia specialist for Pearson Education doing on-set and on-location videography, photgraphy, post-production, and compression for the web.',
   portfolio: 'http://andrewgwallace.com',
   github: 'https://github.com/andrewgwallace',
   twitter: '',
   email: 'andrew.g.wallace@gmail.com',
   image: 'images/string/cropped/andrew.jpg'},
  {name: 'Ben Ticsay',
   intro: 'Since graduating with my degree in international business in 2013, I have done marketing for startups and technology companies. I am looking to immerse further immerse myself in the industry with my newfound skills as a web developer',
   portfolio: 'http://benticsay.com',
   github: 'https://github.com/benticsay',
   twitter: 'http://www.twitter.com/benticsay',
   email: 'benticsay@gmail.com',
   image: 'images/string/cropped/ben.jpg'},
  {name: 'Chris Bajorin',
   intro: 'I worked in finance as an equities trader. A fast-paced work environment demanding quick and confident decision making',
   portfolio: 'http://chrisbajorin.com',
   github: 'https://github.com/cbajorin',
   twitter: '',
   email: 'christopher.bajorin@gmail.com',
   image: 'images/string/cropped/chris.jpg'},
  {name: 'Chris Lee',
   intro: 'With a background in urban studies, I have always enjoyed engaging complex systematic problems. During my time at Warby Parker, I discovered the power of web applications and recognized programming as a place to apply my systematic thinking to interesting challenges.'
   portfolio: 'http://www.christophermarklee.com',
   github: 'https://github.com/chrismlee',
   twitter: '',
   email: 'lee.christophermark@gmail.com',
   image: 'images/string/cropped/chrislee.jpg'},
  {name: 'Dara Mao',
   intro: "I am drawn to logic and arts, which really explains both my fincance background and architectural training. I have found that coding bridges the gap between my disparate worlds and fullfills my interest in creating and building.",
   portfolio: 'http://www.daramao.com',
   github: 'https://github.com/daramao',
   twitter: 'http://www.twitter.com/thedaramao',
   email: 'dara.mao@gmail.com',
   image: 'images/string/cropped/dara.jpg'},
  {name: 'David Montricher',
   intro: 'I was an analyst in the consulting industry, a UN research assistant in Geneva and a junior-architect in Barcelona. I was facinated with Twitter and Airbnb, but I did not want to be a passive consumer. I wanted to make it big.'
   portfolio: 'http://montricher.com',
   github: 'https://github.com/montricher',
   twitter: 'http://www.twitter.com/deinonino',
   email: 'david@montricher.com',
   image: 'images/string/cropped/david.jpg'},
  {name: 'Declan Van Welie',
   intro: "I studied illustration at RISD, and later earned a master`s in art direction at BU. Helping buold MSLO`s ipad editions inspired me to develop the tools I needed to make my design work interactive and innovative ",
   portfolio: 'http://www.decclanvanwelie.com',
   github: 'https://github.com/declanv',
   twitter: '',
   email: 'declanv@gmail.com',
   image: 'images/string/cropped/declan.jpg'},
  {name: 'Elizabeth Goldstein',
   intro: "Before GA, I was involved in the wild west of SEO and internet entrepreneurship. Most people think of living off a laptop on Miami Beach is a dream come true, but there are bigger challenges out there, so I`m learning to code.",
   portfolio: 'http://cira.io/',
   github: 'https://github.com/lizcira',
   twitter: '',
   email: 'liz.cira.goldstein@gmail.com',
   image: 'images/string/cropped/liz.jpg'},
  {name: 'Jane Shin',
   intro: "I'm a creative that started in out in galleries and transitioned into e-commerce. Working with developers made me realize how much intellect and creativity was involved and I wanted to join them.",
   portfolio: 'http://janejhs.com/',
   github: 'http://github.com/janeplural',
   twitter: '',
   email: 'mlle.jshin@gmail.com',
   image: 'images/string/cropped/jane.jpg'},
  {name: 'Joe Park',
   intro: "I was an industry researcher at a clean energy compliance consultancy. Off hours, I was a gamer with a desire to amke websites for my peers",
   portfolio: 'http://joeinthepark.com/',
   github: 'https://github.com/jpark1120/',
   twitter: '',
   email: 'joejwpark@gmail.com',
   image: 'images/string/cropped/joe.jpg'},
  {name: 'Joel Rosenblatt',
   intro: "I left my tiny hometown of Montevideo, Uruguay, to study music in Los Angeles at Musicians Institute. After graduating, I spent the following year working in the film industry, but mainly, traveling the world. Until I discovered programming!",
   portfolio: 'http://www.joelrs.com',
   github: 'https://github.com/klimthaus',
   twitter: '',
   email: 'joelrosenblatt@gmail.com',
   image: 'images/string/cropped/joel.jpg'},
  {name: 'John Randall',
   intro: "I want to build things and save the internet. I worked on policy issues at Harvard's Beekman Center for internet and the Roosevelt Institute. Prior to being a lawyer, I was an audio engineer.",
   portfolio: 'http://www.johnrandall.com',
   github: 'https://github.com/johntrandall',
   twitter: 'twitter.com/johntrandall',
   email: '@gmail.com',
   image: 'images/string/cropped/john.jpg'},
  {name: 'Jonathan Milgrom',
   intro: "I studied math and physics in college. Before discovering GA, I was an attorney in a corporate group at a law firm in NYC. On the side, I started a company that attempted to build a social mapping app.",
   portfolio: 'http://www.jonathanmilgrom.com',
   github: 'https://github.com/jbmilgrom',
   twitter: 'http://twitter.com/jbmilgrom',
   email: 'jbmilgrom@gmail.com',
   image: 'images/string/cropped/jonathan.jpg'},
  {name: 'Keyan Bagheri',
   intro: "I graduated from Old Dominion in VA in 2010 and moved to NYC shortly after. Before discovering GA I worked as branch manager for an investments firm, opening a new office and operating it for over a year.",
   portfolio: 'http://www.keyanbagheri.com/',
   github: 'https://github.com/keyanbagheri',
   twitter: 'http://twitter.com/empathy4apathy',
   email: 'keyanbagheri@gmail.com',
   image: 'images/string/cropped/keyan.jpg'},
  {name: 'Mason Tang',
   intro: "Born and raised in New York City. I majored in economics at Wesleyan University. I have worked as a project manager for a augmented reality startup and I am also an investor and advisor with a creative production house.",
   portfolio: 'http://www.masewillis.com',
   github: 'https://github.com/masewillis',
   twitter: 'http://www.twitter.com/masewillis',
   email: 'mwillistang@gmail.com',
   image: 'images/string/cropped/mason.jpg'},
  {name: 'Nancy Ko',
   intro: "Before GA I was a paralegal for a real estate law firm. One day out of boredom I decided to challenge myself and try coding. A week later I enrolled in GA and haven't stopped coding since.",
   portfolio: 'http://',
   github: 'https://github.com/nancyko',
   twitter: '',
   email: 'konancys@gmail.com',
   image: 'images/string/cropped/nancy.jpg'},
  {name: 'Sophie Laffont',
   intro: "After a career in magazine publishing, I pursued my dream and completed a master`s degree at the Interactive Telecommunications Program at NYU. To further my understanding of digital media, I completed the Web Development Immersive after taking the UX Design Immersive.",
   portfolio: 'http://www.sophielaffont.com',
   github: 'https://github.com/slaffont',
   twitter: 'http://www.twitter.com/slaffont',
   email: 'slaffont@gmail.com',
   image: 'images/string/cropped/sophie.jpg'},
  {name: 'Wilson Chan',
   intro: "I have worked as a graphic designer and special events DJ for numerous fashion brands worldwide. My passion for emerging trends in technology has lead me to GA so I can add more tools under my belt.",
   portfolio: 'http://www.mrwilsondj.com',
   github: 'https://github.com/mrwilsondj',
   twitter: 'http://twitter.com/mrwilsondj',
   email: 'mrwilsondj@gmail.com',
   image: 'images/string/cropped/wilson.jpg'},
]
